# Generated by Django 4.2.28 on 2026-08-22 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CastMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("photo", models.ImageField(blank=True, null=True, upload_to="cast/")),
            ],
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="movie",
            name="certification",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="movie",
            name="duration",
            field=models.PositiveIntegerField(
                blank=True, help_text="Duration in minutes", null=True
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="release_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="movie",
            name="trailer_url",
            field=models.URLField(
                blank=True, help_text="YouTube trailer URL", null=True
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="cast_members",
            field=models.ManyToManyField(
                blank=True, related_name="movies", to="movies.castmember"
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="genres",
            field=models.ManyToManyField(
                blank=True, related_name="movies", to="movies.genre"
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="languages",
            field=models.ManyToManyField(
                blank=True, related_name="movies", to="movies.language"
            ),
        ),
    ]
