# Generated by Django 4.2.28 on 2026-08-24 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_castmember_genre_language_movie_certification_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MoviePoster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="movies/posters/")),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posters",
                        to="movies.movie",
                    ),
                ),
            ],
        ),
    ]
