# Generated by Django 4.2.28 on 2026-08-28 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0005_reviewreport"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="is_verified_viewer",
            field=models.BooleanField(default=False),
        ),
    ]
