# Generated by Django 4.2.28 on 2026-09-20 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0006_review_is_verified_viewer"),
    ]

    operations = [
        migrations.RemoveField(model_name="theater", name="movie",),
        migrations.RemoveField(model_name="theater", name="time",),
        migrations.AddField(
            model_name="theater",
            name="location",
            field=models.CharField(default="Unknown", max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="ShowSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("show_time", models.DateTimeField()),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="show_schedules",
                        to="movies.movie",
                    ),
                ),
                (
                    "theater",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="show_schedules",
                        to="movies.theater",
                    ),
                ),
            ],
        ),
    ]
