# Generated by Django 4.2.28 on 2026-09-24 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0007_remove_theater_movie_remove_theater_time_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="seat", name="is_booked",),
        migrations.RemoveField(model_name="seat", name="theater",),
        migrations.CreateModel(
            name="Screen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "theater",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="screens",
                        to="movies.theater",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="seat",
            name="screen",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="seats",
                to="movies.screen",
            ),
        ),
        migrations.AddField(
            model_name="showschedule",
            name="screen",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="show_schedules",
                to="movies.screen",
            ),
        ),
    ]
