# Generated by Django 4.2.28 on 2026-09-24 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0008_remove_seat_is_booked_remove_seat_theater_screen_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seat",
            name="screen",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="seats",
                to="movies.screen",
            ),
        ),
        migrations.AlterField(
            model_name="showschedule",
            name="screen",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="show_schedules",
                to="movies.screen",
            ),
        ),
    ]
