# Generated by Django 4.2.28 on 2026-09-24 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0009_alter_seat_screen_alter_showschedule_screen"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="seat",
            constraint=models.UniqueConstraint(
                fields=("screen", "seat_number"), name="unique_seat_per_screen"
            ),
        ),
    ]
