# Generated by Django 4.2.28 on 2026-09-24 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0010_seat_unique_seat_per_screen"),
    ]

    operations = [
        migrations.RemoveField(model_name="booking", name="movie",),
        migrations.RemoveField(model_name="booking", name="theater",),
        migrations.AddField(
            model_name="booking",
            name="show_schedule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to="movies.showschedule",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="seat",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to="movies.seat",
            ),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.UniqueConstraint(
                fields=("show_schedule", "seat"), name="unique_seat_per_show"
            ),
        ),
    ]
