# Generated by Django 4.2.28 on 2026-09-24 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0011_remove_booking_movie_remove_booking_theater_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="show_schedule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to="movies.showschedule",
            ),
        ),
    ]
