# Generated by Django 4.2.28 on 2026-09-26 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0012_alter_booking_show_schedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="reserved_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[("reserved", "Reserved"), ("booked", "Booked")],
                default="reserved",
                max_length=20,
            ),
        ),
    ]
