# Generated by Django 4.2.28 on 2026-09-28 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0014_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="showschedule",
            name="ticket_price",
            field=models.DecimalField(decimal_places=2, default=200.0, max_digits=8),
        ),
    ]
