# Generated by Django 4.2.28 on 2026-10-02 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0015_showschedule_ticket_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("success", "Success"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                    ("refunded", "Refunded"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
