# Generated by Django 4.2.28 on 2026-10-02 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0016_alter_payment_payment_status"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["booked_at"], name="movies_book_booked__a7ab7e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(fields=["status"], name="movies_book_status_5cd60b_idx"),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["booked_at", "status"], name="movies_book_booked__7238c1_idx"
            ),
        ),
    ]
