# Generated by Django 4.2.28 on 2026-10-02 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0017_booking_movies_book_booked__a7ab7e_idx_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["created_at"], name="movies_paym_created_5e9beb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["payment_status"], name="movies_paym_payment_82f126_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["created_at", "payment_status"],
                name="movies_paym_created_9eecfa_idx",
            ),
        ),
    ]
