# Generated by Django 4.2.28 on 2026-10-02 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0018_payment_movies_paym_created_5e9beb_idx_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="showschedule",
            index=models.Index(
                fields=["show_time"], name="movies_show_show_ti_497c7a_idx"
            ),
        ),
    ]
